export enum NotificationType {

  USER_HAS_BEEN_ADDED_TO_THE_ORGANIZATION = 'USER_HAS_BEEN_ADDED_TO_THE_ORGANIZATION',
  ROLE_HAS_BEEN_ASSIGNED = 'ROLE_HAS_BEEN_ASSIGNED',
  ROLE_HAS_BEEN_UNASSIGNED = 'ROLE_HAS_BEEN_UNASSIGNED',
  USER_HAS_DECLINED_AN_INVITATION = 'USER_HAS_DECLINED_AN_INVITATION',
  USER_HAS_ACCEPTED_AN_INVITATION = 'USER_HAS_ACCEPTED_AN_INVITATION',
  USER_HAS_BEEN_INVITED_TO_ORGANIZATION = 'USER_HAS_BEEN_INVITED_TO_ORGANIZATION'

}
