name: Frontend CI/CD

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: '19'
          cache: npm
          
      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint || echo "Linting failed, but conituing..."

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular app
        run: npm run build -- --configuration=production
